// Auto-generated. Do not edit!

// (in-package ist_building_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let RoomSequence = require('./RoomSequence.js');
let sensor_msgs = _finder('sensor_msgs');

//-----------------------------------------------------------

class FindRoomSequenceWithCheckpointsResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.checkpoints = null;
      this.sequence_map = null;
    }
    else {
      if (initObj.hasOwnProperty('checkpoints')) {
        this.checkpoints = initObj.checkpoints
      }
      else {
        this.checkpoints = [];
      }
      if (initObj.hasOwnProperty('sequence_map')) {
        this.sequence_map = initObj.sequence_map
      }
      else {
        this.sequence_map = new sensor_msgs.msg.Image();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type FindRoomSequenceWithCheckpointsResult
    // Serialize message field [checkpoints]
    // Serialize the length for message field [checkpoints]
    bufferOffset = _serializer.uint32(obj.checkpoints.length, buffer, bufferOffset);
    obj.checkpoints.forEach((val) => {
      bufferOffset = RoomSequence.serialize(val, buffer, bufferOffset);
    });
    // Serialize message field [sequence_map]
    bufferOffset = sensor_msgs.msg.Image.serialize(obj.sequence_map, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type FindRoomSequenceWithCheckpointsResult
    let len;
    let data = new FindRoomSequenceWithCheckpointsResult(null);
    // Deserialize message field [checkpoints]
    // Deserialize array length for message field [checkpoints]
    len = _deserializer.uint32(buffer, bufferOffset);
    data.checkpoints = new Array(len);
    for (let i = 0; i < len; ++i) {
      data.checkpoints[i] = RoomSequence.deserialize(buffer, bufferOffset)
    }
    // Deserialize message field [sequence_map]
    data.sequence_map = sensor_msgs.msg.Image.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    object.checkpoints.forEach((val) => {
      length += RoomSequence.getMessageSize(val);
    });
    length += sensor_msgs.msg.Image.getMessageSize(object.sequence_map);
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'ist_building_msgs/FindRoomSequenceWithCheckpointsResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'aed0112204502cd11e2b75f3bde2dcf7';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    # result definition
    ist_building_msgs/RoomSequence[] checkpoints			# sequence of checkpoints, should be ordered in optimized traveling salesman sequence
    														# (checkpoint = a clique of rooms close [in terms of robot driving distance] to each other,
    														#               and a central [in terms of rooms in the group] checkpoint location)
    sensor_msgs/Image sequence_map							# map that has the calculated sequence drawn in
    
    ================================================================================
    MSG: ist_building_msgs/RoomSequence
    uint32[] room_indices		# indices of those rooms that belong to one group (connected to a checkpoint,
    							# i.e. the clique of rooms close [in terms of robot driving distance] to each other),
    							# indices should be ordered in optimized traveling salesman sequence
    geometry_msgs/Point32 checkpoint_position_in_pixel			# provides the (x,y)-coordinates of the checkpoint location for this group of rooms [in pixel]
    geometry_msgs/Point32 checkpoint_position_in_meter			# provides the (x,y)-coordinates of the checkpoint location for this group of rooms [in meter]
    ================================================================================
    MSG: geometry_msgs/Point32
    # This contains the position of a point in free space(with 32 bits of precision).
    # It is recommeded to use Point wherever possible instead of Point32.  
    # 
    # This recommendation is to promote interoperability.  
    #
    # This message is designed to take up less space when sending
    # lots of points at once, as in the case of a PointCloud.  
    
    float32 x
    float32 y
    float32 z
    ================================================================================
    MSG: sensor_msgs/Image
    # This message contains an uncompressed image
    # (0, 0) is at top-left corner of image
    #
    
    Header header        # Header timestamp should be acquisition time of image
                         # Header frame_id should be optical frame of camera
                         # origin of frame should be optical center of camera
                         # +x should point to the right in the image
                         # +y should point down in the image
                         # +z should point into to plane of the image
                         # If the frame_id here and the frame_id of the CameraInfo
                         # message associated with the image conflict
                         # the behavior is undefined
    
    uint32 height         # image height, that is, number of rows
    uint32 width          # image width, that is, number of columns
    
    # The legal values for encoding are in file src/image_encodings.cpp
    # If you want to standardize a new string format, join
    # ros-users@lists.sourceforge.net and send an email proposing a new encoding.
    
    string encoding       # Encoding of pixels -- channel meaning, ordering, size
                          # taken from the list of strings in include/sensor_msgs/image_encodings.h
    
    uint8 is_bigendian    # is this data bigendian?
    uint32 step           # Full row length in bytes
    uint8[] data          # actual matrix data, size is (step * rows)
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    # 0: no frame
    # 1: global frame
    string frame_id
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new FindRoomSequenceWithCheckpointsResult(null);
    if (msg.checkpoints !== undefined) {
      resolved.checkpoints = new Array(msg.checkpoints.length);
      for (let i = 0; i < resolved.checkpoints.length; ++i) {
        resolved.checkpoints[i] = RoomSequence.Resolve(msg.checkpoints[i]);
      }
    }
    else {
      resolved.checkpoints = []
    }

    if (msg.sequence_map !== undefined) {
      resolved.sequence_map = sensor_msgs.msg.Image.Resolve(msg.sequence_map)
    }
    else {
      resolved.sequence_map = new sensor_msgs.msg.Image()
    }

    return resolved;
    }
};

module.exports = FindRoomSequenceWithCheckpointsResult;
