
DWAPlannerROS:

 odom_topic: /odom
 #odom_topic: /robot_pose_ekf/odom_combined
 #map_frame: /odom
 map_frame: odom

 max_trans_vel: 0.10
 min_trans_vel: 0.01
 max_vel_x: 0.1
 min_vel_x: 0.0
 max_vel_y: 0.0
 min_vel_y: 0.0
 max_rot_vel: 0.1
 min_rot_vel: -0.1
 acc_lim_x: 10.30
 acc_lim_y: 0.0
 acc_lim_theta: 0.5
 acc_lim_trans: 0.3

 prune_plan: false

 xy_goal_tolerance: 0.1
 yaw_goal_tolerance: 0.5 #before 1
 trans_stopped_vel: 0.1
 rot_stopped_vel: 0.1
 sim_time: 5.0
 sim_granularity: 0.1
 angular_sim_granularity: 0.1
 path_distance_bias: 24.0
 goal_distance_bias: 24.0
 occdist_scale: 0.1 #before 0.1
 twirling_scale: 0.0
 stop_time_buffer: 0.5
 oscillation_reset_dist: 0.05
 oscillation_reset_angle: 0.2
 forward_point_distance: 0.5
 scaling_speed: 0.25
 max_scaling_factor: 0.2
 vx_samples: 20
 vy_samples: 3
 vth_samples: 40

 use_dwa: true
 restore_defaults: false
