global_costmap:
   global_frame: /map
   robot_base_frame: /base_footprint
   update_frequency: 1.5   #1.5
   publish_frequency: 1    # 1.0
   static_map: true
   rolling_window: false
   resolution: 0.02
   transform_tolerance: 1.0
   map_type: costmap
   inflation_radius: 0.4

GlobalPlanner:        
   allow_unknown: true 

   # plugins:
   # - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   # - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}
