#footprint: [[-0.1313, -0.325], [-0.1313, 0.325], [0.2887, 0.325], [0.2887, -0.325]]
local_costmap:
   #global_frame: /odom
   global_frame: odom
   robot_base_frame: /base_footprint
   update_frequency: 1.5
   publish_frequency: 1.0
   static_map: false
   rolling_window: true
   width: 3.0
   height: 3.0
   resolution: 0.02
   transform_tolerance: 1.0
   map_type: costmap

   plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
   - {name: inflation_layer,     type: 'costmap_2d::InflationLayer'}
#   - {name: sonar,               type: 'range_sensor_layer::RangeSensorLayer'}
   
   sonar:
     topics: ["/Ultrasound1"]
     no_readings_timeout: 0.0
