(cl:in-package ist_building_msgs-msg)
(cl:export '(ROOM_INDICES-VAL
          ROOM_INDICES
          CHECKPOINT_POSITION_IN_PIXEL-VAL
          CHECKPOINT_POSITION_IN_PIXEL
          CHECKPOINT_POSITION_IN_METER-VAL
          CHECKPOINT_POSITION_IN_METER
))