; Auto-generated. Do not edit!


(cl:in-package ist_building_msgs-msg)


;//! \htmlinclude FindRoomSequenceWithCheckpointsFeedback.msg.html

(cl:defclass <FindRoomSequenceWithCheckpointsFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass FindRoomSequenceWithCheckpointsFeedback (<FindRoomSequenceWithCheckpointsFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FindRoomSequenceWithCheckpointsFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FindRoomSequenceWithCheckpointsFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ist_building_msgs-msg:<FindRoomSequenceWithCheckpointsFeedback> is deprecated: use ist_building_msgs-msg:FindRoomSequenceWithCheckpointsFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FindRoomSequenceWithCheckpointsFeedback>) ostream)
  "Serializes a message object of type '<FindRoomSequenceWithCheckpointsFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FindRoomSequenceWithCheckpointsFeedback>) istream)
  "Deserializes a message object of type '<FindRoomSequenceWithCheckpointsFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FindRoomSequenceWithCheckpointsFeedback>)))
  "Returns string type for a message object of type '<FindRoomSequenceWithCheckpointsFeedback>"
  "ist_building_msgs/FindRoomSequenceWithCheckpointsFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FindRoomSequenceWithCheckpointsFeedback)))
  "Returns string type for a message object of type 'FindRoomSequenceWithCheckpointsFeedback"
  "ist_building_msgs/FindRoomSequenceWithCheckpointsFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FindRoomSequenceWithCheckpointsFeedback>)))
  "Returns md5sum for a message object of type '<FindRoomSequenceWithCheckpointsFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FindRoomSequenceWithCheckpointsFeedback)))
  "Returns md5sum for a message object of type 'FindRoomSequenceWithCheckpointsFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FindRoomSequenceWithCheckpointsFeedback>)))
  "Returns full string definition for message of type '<FindRoomSequenceWithCheckpointsFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback definition~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FindRoomSequenceWithCheckpointsFeedback)))
  "Returns full string definition for message of type 'FindRoomSequenceWithCheckpointsFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback definition~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FindRoomSequenceWithCheckpointsFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FindRoomSequenceWithCheckpointsFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'FindRoomSequenceWithCheckpointsFeedback
))
