// Generated by gencpp from file ist_building_msgs/RoomSequence.msg
// DO NOT EDIT!


#ifndef IST_BUILDING_MSGS_MESSAGE_ROOMSEQUENCE_H
#define IST_BUILDING_MSGS_MESSAGE_ROOMSEQUENCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point32.h>
#include <geometry_msgs/Point32.h>

namespace ist_building_msgs
{
template <class ContainerAllocator>
struct RoomSequence_
{
  typedef RoomSequence_<ContainerAllocator> Type;

  RoomSequence_()
    : room_indices()
    , checkpoint_position_in_pixel()
    , checkpoint_position_in_meter()  {
    }
  RoomSequence_(const ContainerAllocator& _alloc)
    : room_indices(_alloc)
    , checkpoint_position_in_pixel(_alloc)
    , checkpoint_position_in_meter(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _room_indices_type;
  _room_indices_type room_indices;

   typedef  ::geometry_msgs::Point32_<ContainerAllocator>  _checkpoint_position_in_pixel_type;
  _checkpoint_position_in_pixel_type checkpoint_position_in_pixel;

   typedef  ::geometry_msgs::Point32_<ContainerAllocator>  _checkpoint_position_in_meter_type;
  _checkpoint_position_in_meter_type checkpoint_position_in_meter;





  typedef boost::shared_ptr< ::ist_building_msgs::RoomSequence_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ist_building_msgs::RoomSequence_<ContainerAllocator> const> ConstPtr;

}; // struct RoomSequence_

typedef ::ist_building_msgs::RoomSequence_<std::allocator<void> > RoomSequence;

typedef boost::shared_ptr< ::ist_building_msgs::RoomSequence > RoomSequencePtr;
typedef boost::shared_ptr< ::ist_building_msgs::RoomSequence const> RoomSequenceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ist_building_msgs::RoomSequence_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ist_building_msgs::RoomSequence_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ist_building_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ist_building_msgs': ['/home/ubuntu/zrbase/devel_isolated/ist_building_msgs/share/ist_building_msgs/msg', '/home/ubuntu/zrbase/src/caei/ist_exploration/ist_building_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ist_building_msgs::RoomSequence_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ist_building_msgs::RoomSequence_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ist_building_msgs::RoomSequence_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ist_building_msgs::RoomSequence_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ist_building_msgs::RoomSequence_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ist_building_msgs::RoomSequence_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ist_building_msgs::RoomSequence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5409a76f4f210c24eb6c06e73dcdb711";
  }

  static const char* value(const ::ist_building_msgs::RoomSequence_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5409a76f4f210c24ULL;
  static const uint64_t static_value2 = 0xeb6c06e73dcdb711ULL;
};

template<class ContainerAllocator>
struct DataType< ::ist_building_msgs::RoomSequence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ist_building_msgs/RoomSequence";
  }

  static const char* value(const ::ist_building_msgs::RoomSequence_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ist_building_msgs::RoomSequence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32[] room_indices		# indices of those rooms that belong to one group (connected to a checkpoint,\n\
							# i.e. the clique of rooms close [in terms of robot driving distance] to each other),\n\
							# indices should be ordered in optimized traveling salesman sequence\n\
geometry_msgs/Point32 checkpoint_position_in_pixel			# provides the (x,y)-coordinates of the checkpoint location for this group of rooms [in pixel]\n\
geometry_msgs/Point32 checkpoint_position_in_meter			# provides the (x,y)-coordinates of the checkpoint location for this group of rooms [in meter]\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::ist_building_msgs::RoomSequence_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ist_building_msgs::RoomSequence_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.room_indices);
      stream.next(m.checkpoint_position_in_pixel);
      stream.next(m.checkpoint_position_in_meter);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RoomSequence_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ist_building_msgs::RoomSequence_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ist_building_msgs::RoomSequence_<ContainerAllocator>& v)
  {
    s << indent << "room_indices[]" << std::endl;
    for (size_t i = 0; i < v.room_indices.size(); ++i)
    {
      s << indent << "  room_indices[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.room_indices[i]);
    }
    s << indent << "checkpoint_position_in_pixel: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "  ", v.checkpoint_position_in_pixel);
    s << indent << "checkpoint_position_in_meter: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "  ", v.checkpoint_position_in_meter);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IST_BUILDING_MSGS_MESSAGE_ROOMSEQUENCE_H
