# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ist_building_msgs/FindRoomSequenceWithCheckpointsGoal.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import ist_building_msgs.msg
import std_msgs.msg
import sensor_msgs.msg

class FindRoomSequenceWithCheckpointsGoal(genpy.Message):
  _md5sum = "285d49405549631f016ce37520e05929"
  _type = "ist_building_msgs/FindRoomSequenceWithCheckpointsGoal"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# goal definition
sensor_msgs/Image input_map 				# floor plan map [mono8 format], 0=obstacle or unknown, 255=free space 
float32 map_resolution						# the resolution of the map in [meter/cell]
geometry_msgs/Pose map_origin				# the origin of the map in [meter]
ist_building_msgs/RoomInformation[] room_information_in_pixel		# room data (min/max coordinates, center coordinates) measured in pixels
float64 robot_radius						# the robot footprint radius [m], used for excluding areas from path planning that could not be visited by the robot
geometry_msgs/Pose robot_start_coordinate	# current robot location (used to determine the closest checkpoint in the sequence of checkpoints) [in meter]


================================================================================
MSG: sensor_msgs/Image
# This message contains an uncompressed image
# (0, 0) is at top-left corner of image
#

Header header        # Header timestamp should be acquisition time of image
                     # Header frame_id should be optical frame of camera
                     # origin of frame should be optical center of camera
                     # +x should point to the right in the image
                     # +y should point down in the image
                     # +z should point into to plane of the image
                     # If the frame_id here and the frame_id of the CameraInfo
                     # message associated with the image conflict
                     # the behavior is undefined

uint32 height         # image height, that is, number of rows
uint32 width          # image width, that is, number of columns

# The legal values for encoding are in file src/image_encodings.cpp
# If you want to standardize a new string format, join
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.

string encoding       # Encoding of pixels -- channel meaning, ordering, size
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h

uint8 is_bigendian    # is this data bigendian?
uint32 step           # Full row length in bytes
uint8[] data          # actual matrix data, size is (step * rows)

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: ist_building_msgs/RoomInformation
geometry_msgs/Polygon room_min_max		# first point provides the minimum (x,y)-coordinate values of the rooms, second point provides the maximum (x,y)-coordinate values of the rooms
geometry_msgs/Point32 room_center		# provides the (x,y)-coordinate values of the room centers
================================================================================
MSG: geometry_msgs/Polygon
#A specification of a polygon where the first and last points are assumed to be connected
Point32[] points

================================================================================
MSG: geometry_msgs/Point32
# This contains the position of a point in free space(with 32 bits of precision).
# It is recommeded to use Point wherever possible instead of Point32.  
# 
# This recommendation is to promote interoperability.  
#
# This message is designed to take up less space when sending
# lots of points at once, as in the case of a PointCloud.  

float32 x
float32 y
float32 z"""
  __slots__ = ['input_map','map_resolution','map_origin','room_information_in_pixel','robot_radius','robot_start_coordinate']
  _slot_types = ['sensor_msgs/Image','float32','geometry_msgs/Pose','ist_building_msgs/RoomInformation[]','float64','geometry_msgs/Pose']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       input_map,map_resolution,map_origin,room_information_in_pixel,robot_radius,robot_start_coordinate

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FindRoomSequenceWithCheckpointsGoal, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.input_map is None:
        self.input_map = sensor_msgs.msg.Image()
      if self.map_resolution is None:
        self.map_resolution = 0.
      if self.map_origin is None:
        self.map_origin = geometry_msgs.msg.Pose()
      if self.room_information_in_pixel is None:
        self.room_information_in_pixel = []
      if self.robot_radius is None:
        self.robot_radius = 0.
      if self.robot_start_coordinate is None:
        self.robot_start_coordinate = geometry_msgs.msg.Pose()
    else:
      self.input_map = sensor_msgs.msg.Image()
      self.map_resolution = 0.
      self.map_origin = geometry_msgs.msg.Pose()
      self.room_information_in_pixel = []
      self.robot_radius = 0.
      self.robot_start_coordinate = geometry_msgs.msg.Pose()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.input_map.header.seq, _x.input_map.header.stamp.secs, _x.input_map.header.stamp.nsecs))
      _x = self.input_map.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.input_map.height, _x.input_map.width))
      _x = self.input_map.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_BI().pack(_x.input_map.is_bigendian, _x.input_map.step))
      _x = self.input_map.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_f7d().pack(_x.map_resolution, _x.map_origin.position.x, _x.map_origin.position.y, _x.map_origin.position.z, _x.map_origin.orientation.x, _x.map_origin.orientation.y, _x.map_origin.orientation.z, _x.map_origin.orientation.w))
      length = len(self.room_information_in_pixel)
      buff.write(_struct_I.pack(length))
      for val1 in self.room_information_in_pixel:
        _v1 = val1.room_min_max
        length = len(_v1.points)
        buff.write(_struct_I.pack(length))
        for val3 in _v1.points:
          _x = val3
          buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
        _v2 = val1.room_center
        _x = _v2
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_get_struct_8d().pack(_x.robot_radius, _x.robot_start_coordinate.position.x, _x.robot_start_coordinate.position.y, _x.robot_start_coordinate.position.z, _x.robot_start_coordinate.orientation.x, _x.robot_start_coordinate.orientation.y, _x.robot_start_coordinate.orientation.z, _x.robot_start_coordinate.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.input_map is None:
        self.input_map = sensor_msgs.msg.Image()
      if self.map_origin is None:
        self.map_origin = geometry_msgs.msg.Pose()
      if self.room_information_in_pixel is None:
        self.room_information_in_pixel = None
      if self.robot_start_coordinate is None:
        self.robot_start_coordinate = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.input_map.header.seq, _x.input_map.header.stamp.secs, _x.input_map.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.input_map.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.input_map.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.input_map.height, _x.input_map.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.input_map.encoding = str[start:end].decode('utf-8')
      else:
        self.input_map.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.input_map.is_bigendian, _x.input_map.step,) = _get_struct_BI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.input_map.data = str[start:end]
      _x = self
      start = end
      end += 60
      (_x.map_resolution, _x.map_origin.position.x, _x.map_origin.position.y, _x.map_origin.position.z, _x.map_origin.orientation.x, _x.map_origin.orientation.y, _x.map_origin.orientation.z, _x.map_origin.orientation.w,) = _get_struct_f7d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.room_information_in_pixel = []
      for i in range(0, length):
        val1 = ist_building_msgs.msg.RoomInformation()
        _v3 = val1.room_min_max
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v3.points = []
        for i in range(0, length):
          val3 = geometry_msgs.msg.Point32()
          _x = val3
          start = end
          end += 12
          (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
          _v3.points.append(val3)
        _v4 = val1.room_center
        _x = _v4
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.room_information_in_pixel.append(val1)
      _x = self
      start = end
      end += 64
      (_x.robot_radius, _x.robot_start_coordinate.position.x, _x.robot_start_coordinate.position.y, _x.robot_start_coordinate.position.z, _x.robot_start_coordinate.orientation.x, _x.robot_start_coordinate.orientation.y, _x.robot_start_coordinate.orientation.z, _x.robot_start_coordinate.orientation.w,) = _get_struct_8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.input_map.header.seq, _x.input_map.header.stamp.secs, _x.input_map.header.stamp.nsecs))
      _x = self.input_map.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.input_map.height, _x.input_map.width))
      _x = self.input_map.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_BI().pack(_x.input_map.is_bigendian, _x.input_map.step))
      _x = self.input_map.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_f7d().pack(_x.map_resolution, _x.map_origin.position.x, _x.map_origin.position.y, _x.map_origin.position.z, _x.map_origin.orientation.x, _x.map_origin.orientation.y, _x.map_origin.orientation.z, _x.map_origin.orientation.w))
      length = len(self.room_information_in_pixel)
      buff.write(_struct_I.pack(length))
      for val1 in self.room_information_in_pixel:
        _v5 = val1.room_min_max
        length = len(_v5.points)
        buff.write(_struct_I.pack(length))
        for val3 in _v5.points:
          _x = val3
          buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
        _v6 = val1.room_center
        _x = _v6
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_get_struct_8d().pack(_x.robot_radius, _x.robot_start_coordinate.position.x, _x.robot_start_coordinate.position.y, _x.robot_start_coordinate.position.z, _x.robot_start_coordinate.orientation.x, _x.robot_start_coordinate.orientation.y, _x.robot_start_coordinate.orientation.z, _x.robot_start_coordinate.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.input_map is None:
        self.input_map = sensor_msgs.msg.Image()
      if self.map_origin is None:
        self.map_origin = geometry_msgs.msg.Pose()
      if self.room_information_in_pixel is None:
        self.room_information_in_pixel = None
      if self.robot_start_coordinate is None:
        self.robot_start_coordinate = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.input_map.header.seq, _x.input_map.header.stamp.secs, _x.input_map.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.input_map.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.input_map.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.input_map.height, _x.input_map.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.input_map.encoding = str[start:end].decode('utf-8')
      else:
        self.input_map.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.input_map.is_bigendian, _x.input_map.step,) = _get_struct_BI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.input_map.data = str[start:end]
      _x = self
      start = end
      end += 60
      (_x.map_resolution, _x.map_origin.position.x, _x.map_origin.position.y, _x.map_origin.position.z, _x.map_origin.orientation.x, _x.map_origin.orientation.y, _x.map_origin.orientation.z, _x.map_origin.orientation.w,) = _get_struct_f7d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.room_information_in_pixel = []
      for i in range(0, length):
        val1 = ist_building_msgs.msg.RoomInformation()
        _v7 = val1.room_min_max
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v7.points = []
        for i in range(0, length):
          val3 = geometry_msgs.msg.Point32()
          _x = val3
          start = end
          end += 12
          (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
          _v7.points.append(val3)
        _v8 = val1.room_center
        _x = _v8
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.room_information_in_pixel.append(val1)
      _x = self
      start = end
      end += 64
      (_x.robot_radius, _x.robot_start_coordinate.position.x, _x.robot_start_coordinate.position.y, _x.robot_start_coordinate.position.z, _x.robot_start_coordinate.orientation.x, _x.robot_start_coordinate.orientation.y, _x.robot_start_coordinate.orientation.z, _x.robot_start_coordinate.orientation.w,) = _get_struct_8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_f7d = None
def _get_struct_f7d():
    global _struct_f7d
    if _struct_f7d is None:
        _struct_f7d = struct.Struct("<f7d")
    return _struct_f7d
_struct_BI = None
def _get_struct_BI():
    global _struct_BI
    if _struct_BI is None:
        _struct_BI = struct.Struct("<BI")
    return _struct_BI
_struct_8d = None
def _get_struct_8d():
    global _struct_8d
    if _struct_8d is None:
        _struct_8d = struct.Struct("<8d")
    return _struct_8d
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
