(cl:defpackage ist_building_msgs-srv
  (:use )
  (:export
   "CHECKCOVERAGE"
   "<CHECKCOVERAGE-REQUEST>"
   "CHECKCOVERAGE-REQUEST"
   "<CHECKCOVERAGE-RESPONSE>"
   "CHECKCOVERAGE-RESPONSE"
   "EXTRACTAREAMAPFROMLABELEDMAP"
   "<EXTRACTAREAMAPFROMLABELEDMAP-REQUEST>"
   "EXTRACTAREAMAPFROMLABELEDMAP-REQUEST"
   "<EXTRACTAREAMAPFROMLABELEDMAP-RESPONSE>"
   "EXTRACTAREAMAPFROMLABELEDMAP-RESPONSE"
  ))

