// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ist_slam/pose_graph/proto/pose_graph_data.proto

#ifndef PROTOBUF_ist_5fslam_2fpose_5fgraph_2fproto_2fpose_5fgraph_5fdata_2eproto__INCLUDED
#define PROTOBUF_ist_5fslam_2fpose_5fgraph_2fproto_2fpose_5fgraph_5fdata_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ist_slam/pose_graph/proto/node.pb.h"
#include "ist_slam/pose_graph/proto/constraint.pb.h"
// @@protoc_insertion_point(includes)
namespace ist_slam {
namespace pose_graph {
namespace proto {
class PoseGraphData;
class PoseGraphDataDefaultTypeInternal;
extern PoseGraphDataDefaultTypeInternal _PoseGraphData_default_instance_;
}  // namespace proto
}  // namespace pose_graph
}  // namespace ist_slam

namespace ist_slam {
namespace pose_graph {
namespace proto {

namespace protobuf_ist_5fslam_2fpose_5fgraph_2fproto_2fpose_5fgraph_5fdata_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_ist_5fslam_2fpose_5fgraph_2fproto_2fpose_5fgraph_5fdata_2eproto

// ===================================================================

class PoseGraphData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ist_slam.pose_graph.proto.PoseGraphData) */ {
 public:
  PoseGraphData();
  virtual ~PoseGraphData();

  PoseGraphData(const PoseGraphData& from);

  inline PoseGraphData& operator=(const PoseGraphData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PoseGraphData(PoseGraphData&& from) noexcept
    : PoseGraphData() {
    *this = ::std::move(from);
  }

  inline PoseGraphData& operator=(PoseGraphData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PoseGraphData& default_instance();

  static inline const PoseGraphData* internal_default_instance() {
    return reinterpret_cast<const PoseGraphData*>(
               &_PoseGraphData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(PoseGraphData* other);
  friend void swap(PoseGraphData& a, PoseGraphData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PoseGraphData* New() const PROTOBUF_FINAL { return New(NULL); }

  PoseGraphData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PoseGraphData& from);
  void MergeFrom(const PoseGraphData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PoseGraphData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ist_slam.pose_graph.proto.Node nodes = 1;
  int nodes_size() const;
  void clear_nodes();
  static const int kNodesFieldNumber = 1;
  const ::ist_slam::pose_graph::proto::Node& nodes(int index) const;
  ::ist_slam::pose_graph::proto::Node* mutable_nodes(int index);
  ::ist_slam::pose_graph::proto::Node* add_nodes();
  ::google::protobuf::RepeatedPtrField< ::ist_slam::pose_graph::proto::Node >*
      mutable_nodes();
  const ::google::protobuf::RepeatedPtrField< ::ist_slam::pose_graph::proto::Node >&
      nodes() const;

  // repeated .ist_slam.pose_graph.proto.Constraint constraints = 2;
  int constraints_size() const;
  void clear_constraints();
  static const int kConstraintsFieldNumber = 2;
  const ::ist_slam::pose_graph::proto::Constraint& constraints(int index) const;
  ::ist_slam::pose_graph::proto::Constraint* mutable_constraints(int index);
  ::ist_slam::pose_graph::proto::Constraint* add_constraints();
  ::google::protobuf::RepeatedPtrField< ::ist_slam::pose_graph::proto::Constraint >*
      mutable_constraints();
  const ::google::protobuf::RepeatedPtrField< ::ist_slam::pose_graph::proto::Constraint >&
      constraints() const;

  // @@protoc_insertion_point(class_scope:ist_slam.pose_graph.proto.PoseGraphData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::ist_slam::pose_graph::proto::Node > nodes_;
  ::google::protobuf::RepeatedPtrField< ::ist_slam::pose_graph::proto::Constraint > constraints_;
  mutable int _cached_size_;
  friend struct protobuf_ist_5fslam_2fpose_5fgraph_2fproto_2fpose_5fgraph_5fdata_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PoseGraphData

// repeated .ist_slam.pose_graph.proto.Node nodes = 1;
inline int PoseGraphData::nodes_size() const {
  return nodes_.size();
}
inline void PoseGraphData::clear_nodes() {
  nodes_.Clear();
}
inline const ::ist_slam::pose_graph::proto::Node& PoseGraphData::nodes(int index) const {
  // @@protoc_insertion_point(field_get:ist_slam.pose_graph.proto.PoseGraphData.nodes)
  return nodes_.Get(index);
}
inline ::ist_slam::pose_graph::proto::Node* PoseGraphData::mutable_nodes(int index) {
  // @@protoc_insertion_point(field_mutable:ist_slam.pose_graph.proto.PoseGraphData.nodes)
  return nodes_.Mutable(index);
}
inline ::ist_slam::pose_graph::proto::Node* PoseGraphData::add_nodes() {
  // @@protoc_insertion_point(field_add:ist_slam.pose_graph.proto.PoseGraphData.nodes)
  return nodes_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ist_slam::pose_graph::proto::Node >*
PoseGraphData::mutable_nodes() {
  // @@protoc_insertion_point(field_mutable_list:ist_slam.pose_graph.proto.PoseGraphData.nodes)
  return &nodes_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ist_slam::pose_graph::proto::Node >&
PoseGraphData::nodes() const {
  // @@protoc_insertion_point(field_list:ist_slam.pose_graph.proto.PoseGraphData.nodes)
  return nodes_;
}

// repeated .ist_slam.pose_graph.proto.Constraint constraints = 2;
inline int PoseGraphData::constraints_size() const {
  return constraints_.size();
}
inline void PoseGraphData::clear_constraints() {
  constraints_.Clear();
}
inline const ::ist_slam::pose_graph::proto::Constraint& PoseGraphData::constraints(int index) const {
  // @@protoc_insertion_point(field_get:ist_slam.pose_graph.proto.PoseGraphData.constraints)
  return constraints_.Get(index);
}
inline ::ist_slam::pose_graph::proto::Constraint* PoseGraphData::mutable_constraints(int index) {
  // @@protoc_insertion_point(field_mutable:ist_slam.pose_graph.proto.PoseGraphData.constraints)
  return constraints_.Mutable(index);
}
inline ::ist_slam::pose_graph::proto::Constraint* PoseGraphData::add_constraints() {
  // @@protoc_insertion_point(field_add:ist_slam.pose_graph.proto.PoseGraphData.constraints)
  return constraints_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ist_slam::pose_graph::proto::Constraint >*
PoseGraphData::mutable_constraints() {
  // @@protoc_insertion_point(field_mutable_list:ist_slam.pose_graph.proto.PoseGraphData.constraints)
  return &constraints_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ist_slam::pose_graph::proto::Constraint >&
PoseGraphData::constraints() const {
  // @@protoc_insertion_point(field_list:ist_slam.pose_graph.proto.PoseGraphData.constraints)
  return constraints_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace proto
}  // namespace pose_graph
}  // namespace ist_slam

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ist_5fslam_2fpose_5fgraph_2fproto_2fpose_5fgraph_5fdata_2eproto__INCLUDED
