// Generated by gencpp from file speed_param/speed.msg
// DO NOT EDIT!


#ifndef SPEED_PARAM_MESSAGE_SPEED_H
#define SPEED_PARAM_MESSAGE_SPEED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace speed_param
{
template <class ContainerAllocator>
struct speed_
{
  typedef speed_<ContainerAllocator> Type;

  speed_()
    : line(0.0)
    , angular(0.0)  {
    }
  speed_(const ContainerAllocator& _alloc)
    : line(0.0)
    , angular(0.0)  {
  (void)_alloc;
    }



   typedef float _line_type;
  _line_type line;

   typedef float _angular_type;
  _angular_type angular;





  typedef boost::shared_ptr< ::speed_param::speed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::speed_param::speed_<ContainerAllocator> const> ConstPtr;

}; // struct speed_

typedef ::speed_param::speed_<std::allocator<void> > speed;

typedef boost::shared_ptr< ::speed_param::speed > speedPtr;
typedef boost::shared_ptr< ::speed_param::speed const> speedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::speed_param::speed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::speed_param::speed_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace speed_param

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'speed_param': ['/home/ubuntu/zrbase/src/speed_param/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::speed_param::speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::speed_param::speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speed_param::speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speed_param::speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speed_param::speed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speed_param::speed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::speed_param::speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "06684d5be7e1ff5a383443515a74e02c";
  }

  static const char* value(const ::speed_param::speed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x06684d5be7e1ff5aULL;
  static const uint64_t static_value2 = 0x383443515a74e02cULL;
};

template<class ContainerAllocator>
struct DataType< ::speed_param::speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "speed_param/speed";
  }

  static const char* value(const ::speed_param::speed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::speed_param::speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 line\n\
float32 angular\n\
";
  }

  static const char* value(const ::speed_param::speed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::speed_param::speed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.line);
      stream.next(m.angular);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct speed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::speed_param::speed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::speed_param::speed_<ContainerAllocator>& v)
  {
    s << indent << "line: ";
    Printer<float>::stream(s, indent + "  ", v.line);
    s << indent << "angular: ";
    Printer<float>::stream(s, indent + "  ", v.angular);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPEED_PARAM_MESSAGE_SPEED_H
